version: '3'

services:

  redis:
    image: "redis:4"
    container_name: ai_redis
    ports:
     - "6379"

  web:
    build: .
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "80:80"
    container_name: ai_mod

